openapi: 3.0.3
info:
  title: Atgenomix SeqsLab V3 platform API
  version: 3.0.0 (healthcare-v3)
  description: GA4GH-compliant RESTful API apps in Atgenomix SeqsLab platform, the
    cloud-native enterprise biomedical informatics platform.
paths:
  /healthcare/v3/pages/:
    get:
      operationId: healthcare_v3_pages_list
      description: |-
        Enforces object-level permissions in ``rest_framework.viewsets.ViewSet``,
        deriving the permission type from the particular action to be performed..

        As with ``rules.contrib.views.AutoPermissionRequiredMixin``, this only works when
        model permissions are registered using ``rules.contrib.models.RulesModelMixin``.
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - pages
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedPagesList'
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData:
                  value:
                    detail: 'Received a KeyError when attempting to get a value for
                      field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and does not
                      match any attribute or key on the `dict` instance. Original
                      exception text was: ''workspace''.'
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data
                  description: Serializer format is not the same as the RDB data
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided:
                  value:
                    detail: Authentication credentials were not provided
                    code: not_authenticated
                  summary: Authentication credentials were not provided
                  description: Authentication credentials were not provided
                GivenTokenIsNotValidForAnyTokenType:
                  value:
                    detail: Given token is not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token is not valid for any token type
                  description: Given token is not valid for any token type
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token is not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction:
                  value:
                    detail: You do not have permission to perform this action
                    code: permission_denied
                  summary: You do not have permission to perform this action
                  description: You do not have permission to perform this action
          description: ''
    post:
      operationId: healthcare_v3_pages_create
      description: |-
        Enforces object-level permissions in ``rest_framework.viewsets.ViewSet``,
        deriving the permission type from the particular action to be performed..

        As with ``rules.contrib.views.AutoPermissionRequiredMixin``, this only works when
        model permissions are registered using ``rules.contrib.models.RulesModelMixin``.
      tags:
      - pages
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PagesRequest'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pages'
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData:
                  value:
                    detail: 'Received a KeyError when attempting to get a value for
                      field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and does not
                      match any attribute or key on the `dict` instance. Original
                      exception text was: ''workspace''.'
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data
                  description: Serializer format is not the same as the RDB data
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided:
                  value:
                    detail: Authentication credentials were not provided
                    code: not_authenticated
                  summary: Authentication credentials were not provided
                  description: Authentication credentials were not provided
                GivenTokenIsNotValidForAnyTokenType:
                  value:
                    detail: Given token is not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token is not valid for any token type
                  description: Given token is not valid for any token type
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token is not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction:
                  value:
                    detail: You do not have permission to perform this action
                    code: permission_denied
                  summary: You do not have permission to perform this action
                  description: You do not have permission to perform this action
          description: ''
  /healthcare/v3/pages/{pages_pk}/charts/{id}/:
    get:
      operationId: healthcare_v3_pages_charts_retrieve
      description: |-
        Enforces object-level permissions in ``rest_framework.viewsets.ViewSet``,
        deriving the permission type from the particular action to be performed..

        As with ``rules.contrib.views.AutoPermissionRequiredMixin``, this only works when
        model permissions are registered using ``rules.contrib.models.RulesModelMixin``.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this charts.
        required: true
      - in: path
        name: pages_pk
        schema:
          type: string
        required: true
      tags:
      - charts
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Charts'
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData:
                  value:
                    detail: 'Received a KeyError when attempting to get a value for
                      field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and does not
                      match any attribute or key on the `dict` instance. Original
                      exception text was: ''workspace''.'
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data
                  description: Serializer format is not the same as the RDB data
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided:
                  value:
                    detail: Authentication credentials were not provided
                    code: not_authenticated
                  summary: Authentication credentials were not provided
                  description: Authentication credentials were not provided
                GivenTokenIsNotValidForAnyTokenType:
                  value:
                    detail: Given token is not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token is not valid for any token type
                  description: Given token is not valid for any token type
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token is not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction:
                  value:
                    detail: You do not have permission to perform this action
                    code: permission_denied
                  summary: You do not have permission to perform this action
                  description: You do not have permission to perform this action
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                NotFound:
                  value:
                    detail: No <object> matches the given query
                    code: object_does_not_exist
                  summary: Not found
                  description: Not found
          description: ''
    put:
      operationId: healthcare_v3_pages_charts_update
      description: |-
        Enforces object-level permissions in ``rest_framework.viewsets.ViewSet``,
        deriving the permission type from the particular action to be performed..

        As with ``rules.contrib.views.AutoPermissionRequiredMixin``, this only works when
        model permissions are registered using ``rules.contrib.models.RulesModelMixin``.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this charts.
        required: true
      - in: path
        name: pages_pk
        schema:
          type: string
        required: true
      tags:
      - charts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChartsRequest'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Charts'
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData:
                  value:
                    detail: 'Received a KeyError when attempting to get a value for
                      field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and does not
                      match any attribute or key on the `dict` instance. Original
                      exception text was: ''workspace''.'
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data
                  description: Serializer format is not the same as the RDB data
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided:
                  value:
                    detail: Authentication credentials were not provided
                    code: not_authenticated
                  summary: Authentication credentials were not provided
                  description: Authentication credentials were not provided
                GivenTokenIsNotValidForAnyTokenType:
                  value:
                    detail: Given token is not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token is not valid for any token type
                  description: Given token is not valid for any token type
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token is not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction:
                  value:
                    detail: You do not have permission to perform this action
                    code: permission_denied
                  summary: You do not have permission to perform this action
                  description: You do not have permission to perform this action
          description: ''
    patch:
      operationId: healthcare_v3_pages_charts_partial_update
      description: |-
        Enforces object-level permissions in ``rest_framework.viewsets.ViewSet``,
        deriving the permission type from the particular action to be performed..

        As with ``rules.contrib.views.AutoPermissionRequiredMixin``, this only works when
        model permissions are registered using ``rules.contrib.models.RulesModelMixin``.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this charts.
        required: true
      - in: path
        name: pages_pk
        schema:
          type: string
        required: true
      tags:
      - charts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedChartsRequest'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Charts'
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData:
                  value:
                    detail: 'Received a KeyError when attempting to get a value for
                      field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and does not
                      match any attribute or key on the `dict` instance. Original
                      exception text was: ''workspace''.'
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data
                  description: Serializer format is not the same as the RDB data
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided:
                  value:
                    detail: Authentication credentials were not provided
                    code: not_authenticated
                  summary: Authentication credentials were not provided
                  description: Authentication credentials were not provided
                GivenTokenIsNotValidForAnyTokenType:
                  value:
                    detail: Given token is not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token is not valid for any token type
                  description: Given token is not valid for any token type
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token is not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction:
                  value:
                    detail: You do not have permission to perform this action
                    code: permission_denied
                  summary: You do not have permission to perform this action
                  description: You do not have permission to perform this action
          description: ''
    delete:
      operationId: healthcare_v3_pages_charts_destroy
      description: |-
        Enforces object-level permissions in ``rest_framework.viewsets.ViewSet``,
        deriving the permission type from the particular action to be performed..

        As with ``rules.contrib.views.AutoPermissionRequiredMixin``, this only works when
        model permissions are registered using ``rules.contrib.models.RulesModelMixin``.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this charts.
        required: true
      - in: path
        name: pages_pk
        schema:
          type: string
        required: true
      tags:
      - charts
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData:
                  value:
                    detail: 'Received a KeyError when attempting to get a value for
                      field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and does not
                      match any attribute or key on the `dict` instance. Original
                      exception text was: ''workspace''.'
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data
                  description: Serializer format is not the same as the RDB data
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided:
                  value:
                    detail: Authentication credentials were not provided
                    code: not_authenticated
                  summary: Authentication credentials were not provided
                  description: Authentication credentials were not provided
                GivenTokenIsNotValidForAnyTokenType:
                  value:
                    detail: Given token is not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token is not valid for any token type
                  description: Given token is not valid for any token type
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token is not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction:
                  value:
                    detail: You do not have permission to perform this action
                    code: permission_denied
                  summary: You do not have permission to perform this action
                  description: You do not have permission to perform this action
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                NotFound:
                  value:
                    detail: No <object> matches the given query
                    code: object_does_not_exist
                  summary: Not found
                  description: Not found
          description: ''
  /healthcare/v3/pages/{id}/:
    get:
      operationId: healthcare_v3_pages_retrieve
      description: |-
        Enforces object-level permissions in ``rest_framework.viewsets.ViewSet``,
        deriving the permission type from the particular action to be performed..

        As with ``rules.contrib.views.AutoPermissionRequiredMixin``, this only works when
        model permissions are registered using ``rules.contrib.models.RulesModelMixin``.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this pages.
        required: true
      tags:
      - pages
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pages'
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData:
                  value:
                    detail: 'Received a KeyError when attempting to get a value for
                      field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and does not
                      match any attribute or key on the `dict` instance. Original
                      exception text was: ''workspace''.'
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data
                  description: Serializer format is not the same as the RDB data
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided:
                  value:
                    detail: Authentication credentials were not provided
                    code: not_authenticated
                  summary: Authentication credentials were not provided
                  description: Authentication credentials were not provided
                GivenTokenIsNotValidForAnyTokenType:
                  value:
                    detail: Given token is not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token is not valid for any token type
                  description: Given token is not valid for any token type
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token is not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction:
                  value:
                    detail: You do not have permission to perform this action
                    code: permission_denied
                  summary: You do not have permission to perform this action
                  description: You do not have permission to perform this action
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                NotFound:
                  value:
                    detail: No <object> matches the given query
                    code: object_does_not_exist
                  summary: Not found
                  description: Not found
          description: ''
    put:
      operationId: healthcare_v3_pages_update
      description: |-
        Enforces object-level permissions in ``rest_framework.viewsets.ViewSet``,
        deriving the permission type from the particular action to be performed..

        As with ``rules.contrib.views.AutoPermissionRequiredMixin``, this only works when
        model permissions are registered using ``rules.contrib.models.RulesModelMixin``.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this pages.
        required: true
      tags:
      - pages
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PagesRequest'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pages'
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData:
                  value:
                    detail: 'Received a KeyError when attempting to get a value for
                      field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and does not
                      match any attribute or key on the `dict` instance. Original
                      exception text was: ''workspace''.'
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data
                  description: Serializer format is not the same as the RDB data
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided:
                  value:
                    detail: Authentication credentials were not provided
                    code: not_authenticated
                  summary: Authentication credentials were not provided
                  description: Authentication credentials were not provided
                GivenTokenIsNotValidForAnyTokenType:
                  value:
                    detail: Given token is not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token is not valid for any token type
                  description: Given token is not valid for any token type
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token is not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction:
                  value:
                    detail: You do not have permission to perform this action
                    code: permission_denied
                  summary: You do not have permission to perform this action
                  description: You do not have permission to perform this action
          description: ''
    patch:
      operationId: healthcare_v3_pages_partial_update
      description: |-
        Enforces object-level permissions in ``rest_framework.viewsets.ViewSet``,
        deriving the permission type from the particular action to be performed..

        As with ``rules.contrib.views.AutoPermissionRequiredMixin``, this only works when
        model permissions are registered using ``rules.contrib.models.RulesModelMixin``.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this pages.
        required: true
      tags:
      - pages
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPagesRequest'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pages'
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData:
                  value:
                    detail: 'Received a KeyError when attempting to get a value for
                      field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and does not
                      match any attribute or key on the `dict` instance. Original
                      exception text was: ''workspace''.'
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data
                  description: Serializer format is not the same as the RDB data
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided:
                  value:
                    detail: Authentication credentials were not provided
                    code: not_authenticated
                  summary: Authentication credentials were not provided
                  description: Authentication credentials were not provided
                GivenTokenIsNotValidForAnyTokenType:
                  value:
                    detail: Given token is not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token is not valid for any token type
                  description: Given token is not valid for any token type
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token is not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction:
                  value:
                    detail: You do not have permission to perform this action
                    code: permission_denied
                  summary: You do not have permission to perform this action
                  description: You do not have permission to perform this action
          description: ''
    delete:
      operationId: healthcare_v3_pages_destroy
      description: |-
        Enforces object-level permissions in ``rest_framework.viewsets.ViewSet``,
        deriving the permission type from the particular action to be performed..

        As with ``rules.contrib.views.AutoPermissionRequiredMixin``, this only works when
        model permissions are registered using ``rules.contrib.models.RulesModelMixin``.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this pages.
        required: true
      tags:
      - pages
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData:
                  value:
                    detail: 'Received a KeyError when attempting to get a value for
                      field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and does not
                      match any attribute or key on the `dict` instance. Original
                      exception text was: ''workspace''.'
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data
                  description: Serializer format is not the same as the RDB data
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided:
                  value:
                    detail: Authentication credentials were not provided
                    code: not_authenticated
                  summary: Authentication credentials were not provided
                  description: Authentication credentials were not provided
                GivenTokenIsNotValidForAnyTokenType:
                  value:
                    detail: Given token is not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token is not valid for any token type
                  description: Given token is not valid for any token type
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token is not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction:
                  value:
                    detail: You do not have permission to perform this action
                    code: permission_denied
                  summary: You do not have permission to perform this action
                  description: You do not have permission to perform this action
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                NotFound:
                  value:
                    detail: No <object> matches the given query
                    code: object_does_not_exist
                  summary: Not found
                  description: Not found
          description: ''
  /healthcare/v3/schema/:
    get:
      operationId: root_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      security:
      - jwtAuth: []
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData:
                  value:
                    detail: 'Received a KeyError when attempting to get a value for
                      field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and does not
                      match any attribute or key on the `dict` instance. Original
                      exception text was: ''workspace''.'
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data
                  description: Serializer format is not the same as the RDB data
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided:
                  value:
                    detail: Authentication credentials were not provided
                    code: not_authenticated
                  summary: Authentication credentials were not provided
                  description: Authentication credentials were not provided
                GivenTokenIsNotValidForAnyTokenType:
                  value:
                    detail: Given token is not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token is not valid for any token type
                  description: Given token is not valid for any token type
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token is not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction:
                  value:
                    detail: You do not have permission to perform this action
                    code: permission_denied
                  summary: You do not have permission to perform this action
                  description: You do not have permission to perform this action
          description: ''
components:
  schemas:
    Charts:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        query:
          type: string
        variables:
          type: object
          additionalProperties: {}
        model:
          $ref: '#/components/schemas/ModelEnum'
        version:
          type: string
          format: date-time
          readOnly: true
        identifier:
          type: object
          additionalProperties: {}
          nullable: true
      required:
      - id
      - model
      - query
      - variables
      - version
    ChartsRequest:
      type: object
      properties:
        query:
          type: string
          minLength: 1
        variables:
          type: object
          additionalProperties: {}
        model:
          $ref: '#/components/schemas/ModelEnum'
        identifier:
          type: object
          additionalProperties: {}
          nullable: true
      required:
      - model
      - query
      - variables
    ModelEnum:
      enum:
      - Phenopacket
      - Biosample
      - Measurement
      - PhenotypicFeature
      - Individual
      - Interpretation
      - OntologyClass
      type: string
      description: |-
        * `Phenopacket` - Phenopacket
        * `Biosample` - Biosample
        * `Measurement` - Measurement
        * `PhenotypicFeature` - PhenotypicFeature
        * `Individual` - Individual
        * `Interpretation` - Interpretation
        * `OntologyClass` - OntologyClass
    Pages:
      type: object
      description: Adds nested create feature
      properties:
        id:
          type: integer
          readOnly: true
        charts:
          type: array
          items:
            $ref: '#/components/schemas/Charts'
        name:
          type: string
          maxLength: 255
        description:
          type: string
          nullable: true
        organization:
          type: string
          readOnly: true
        user:
          type: string
          readOnly: true
          nullable: true
      required:
      - charts
      - id
      - name
      - organization
      - user
    PagesRequest:
      type: object
      description: Adds nested create feature
      properties:
        charts:
          type: array
          items:
            $ref: '#/components/schemas/ChartsRequest'
        name:
          type: string
          minLength: 1
          maxLength: 255
        description:
          type: string
          nullable: true
          minLength: 1
      required:
      - charts
      - name
    PaginatedPagesList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Pages'
    PatchedChartsRequest:
      type: object
      properties:
        query:
          type: string
          minLength: 1
        variables:
          type: object
          additionalProperties: {}
        model:
          $ref: '#/components/schemas/ModelEnum'
        identifier:
          type: object
          additionalProperties: {}
          nullable: true
    PatchedPagesRequest:
      type: object
      description: Adds nested create feature
      properties:
        charts:
          type: array
          items:
            $ref: '#/components/schemas/ChartsRequest'
        name:
          type: string
          minLength: 1
          maxLength: 255
        description:
          type: string
          nullable: true
          minLength: 1
    StandardSerializers:
      type: object
      properties:
        detail:
          type: string
          description: The detailed error message.
        msg:
          type: string
          default: Authentication credentials were not provided
          description: A detailed error message.
        code:
          type: string
          description: The error code.
      required:
      - code
      - detail
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
