openapi: 3.0.3
info:
  title: Atgenomix SeqsLab V3 platform API
  version: 3.0.0
  description: GA4GH-compliant RESTful API apps in Atgenomix SeqsLab platform, the
    cloud-native enterprise biomedical informatics platform.
paths:
  /label/v3/labels/:
    get:
      operationId: list label under user
      description: Return the Label under the User
      tags:
      - label
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Label'
              examples:
                ReturnTheLabelUnderUser:
                  value:
                    data:
                    - data:
                        name: Label name
                        extra:
                          color: hex code
                      id: node id
                      children:
                      - data:
                          name: Label name
                          extra:
                            color: hex code
                        id: node id
                    - data:
                        name: Label name1
                        extra:
                          color: hex code
                      id: node id
                    count: 3
                  summary: Return the Label under user
                  description: Return the Label tree under user, the return list will
                    under the data.
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData.:
                  value:
                    detail: |-
                      Got KeyError when attempting to get a value for field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.
                      Original exception text was: 'workspace'.
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data.
                  description: Serializer format is not same as the RDB data.
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided.:
                  value:
                    detail: Authentication credentials were not provided.
                    code: not_authenticated
                  summary: Authentication credentials were not provided.
                  description: Authentication credentials were not provided.
                GivenTokenNotValidForAnyTokenType:
                  value:
                    detail: Given token not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token not valid for any token type
                  description: Given token is not valid for any token type.
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction.:
                  value:
                    detail: You do not have permission to perform this action.
                    code: permission_denied
                  summary: You do not have permission to perform this action.
                  description: You do not have permission to perform this action.
          description: ''
    post:
      operationId: create label by user
      description: Create the Label under the User root
      tags:
      - label
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelRequest'
            examples:
              SingleTree:
                value:
                - data:
                    name: Label name
                    extra:
                      color: hex code
                summary: Single Tree
                description: 'This request body is JSON. For this JSON, it is the
                  list. <br/>Each list contains many dictionary of data. <br/>Each
                  dictionary of data means the one root tree.  Each root tree must
                  contain data. <br/>When the root tree has the children node, pass
                  children in the dictionary. <br/>data is the dictionary; each dictionary
                  of data must contain two parameters, name(string) and extra(dictionary).
                  <br/>children mean the children of the data, which is the list.
                  One children can contain many dictionary of data. '
              SingleTreeWithChildren:
                value:
                - data:
                    name: Label name
                    extra:
                      color: hex code
                  children:
                  - data:
                      name: Label name
                      extra:
                        color: hex code
                summary: Single Tree With Children
                description: 'This request body is JSON. For this JSON, it is the
                  list. <br/>Each list contains many dictionary of data. <br/>Each
                  dictionary of data means the one root tree.  Each root tree must
                  contain data. <br/>When the root tree has the children node, pass
                  children in the dictionary. <br/>data is the dictionary; each dictionary
                  of data must contain two parameters, name(string) and extra(dictionary).
                  <br/>children mean the children of the data, which is the list.
                  One children can contain many dictionary of data. '
              MultipleTreeWithChildren:
                value:
                - data:
                    name: Label name
                    extra:
                      color: hex code
                  children:
                  - data:
                      name: Label name
                      extra:
                        color: hex code
                - data:
                    name: Label name1
                    extra:
                      color: hex code
                summary: Multiple Tree With Children
                description: 'This request body is JSON. For this JSON, it is the
                  list. <br/>Each list contains many dictionary of data. <br/>Each
                  dictionary of data means the one root tree.  Each root tree must
                  contain data. <br/>When the root tree has the children node, pass
                  children in the dictionary. <br/>data is the dictionary; each dictionary
                  of data must contain two parameters, name(string) and extra(dictionary).
                  <br/>children mean the children of the data, which is the list.
                  One children can contain many dictionary of data. '
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          description: No response body
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData.:
                  value:
                    detail: |-
                      Got KeyError when attempting to get a value for field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.
                      Original exception text was: 'workspace'.
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data.
                  description: Serializer format is not same as the RDB data.
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided.:
                  value:
                    detail: Authentication credentials were not provided.
                    code: not_authenticated
                  summary: Authentication credentials were not provided.
                  description: Authentication credentials were not provided.
                GivenTokenNotValidForAnyTokenType:
                  value:
                    detail: Given token not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token not valid for any token type
                  description: Given token is not valid for any token type.
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction.:
                  value:
                    detail: You do not have permission to perform this action.
                    code: permission_denied
                  summary: You do not have permission to perform this action.
                  description: You do not have permission to perform this action.
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                BadRequest:
                  value:
                    error:
                      code: bad_request
                      messages: duplicates name in root node
                  summary: Bad Request
                  description: 400 Bad Request
          description: ''
  /label/v3/labels/{id}/:
    get:
      operationId: label_v3_labels_list
      description: Return the Label tree by the label id
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this label.
        required: true
      tags:
      - label
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LabelID'
              examples:
                ReturnTheLabelTreeByTheLabelId:
                  value:
                    data:
                    - data:
                        name: Label name
                        extra:
                          color: hex code
                      id: node id
                      children:
                      - data:
                          name: Label name
                          extra:
                            color: hex code
                        id: node id
                    count: 2
                  summary: Return the Label tree by the label id
                  description: Return the Label tree by the label id, the return list
                    will under the data.
          description: ''
        '404':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NotFound'
              examples:
                NotFound:
                  value:
                    detail: Not found.
                    status: 404
                  summary: Not Found
                  description: 404 Not Found
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData.:
                  value:
                    detail: |-
                      Got KeyError when attempting to get a value for field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.
                      Original exception text was: 'workspace'.
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data.
                  description: Serializer format is not same as the RDB data.
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided.:
                  value:
                    detail: Authentication credentials were not provided.
                    code: not_authenticated
                  summary: Authentication credentials were not provided.
                  description: Authentication credentials were not provided.
                GivenTokenNotValidForAnyTokenType:
                  value:
                    detail: Given token not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token not valid for any token type
                  description: Given token is not valid for any token type.
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction.:
                  value:
                    detail: You do not have permission to perform this action.
                    code: permission_denied
                  summary: You do not have permission to perform this action.
                  description: You do not have permission to perform this action.
          description: ''
    post:
      operationId: label_v3_labels_create
      description: Create label inherit from label id
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this label.
        required: true
      tags:
      - label
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelIDPostRequest'
            examples:
              SingleTree:
                value:
                - data:
                    name: Label name
                    extra:
                      color: hex code
                summary: Single Tree
                description: 'This request body is JSON. For this JSON, it is the
                  list. <br/>Each list contains many dictionary of data. <br/>Each
                  dictionary of data means the one root tree.  Each root tree must
                  contain data. <br/>When the root tree has the children node, pass
                  children in the dictionary. <br/>data is the dictionary; each dictionary
                  of data must contain two parameters, name(string) and extra(dictionary).
                  <br/>children mean the children of the data, which is the list.
                  One children can contain many dictionary of data. '
              SingleTreeWithChildren:
                value:
                - data:
                    name: Label name
                    extra:
                      color: hex code
                  children:
                  - data:
                      name: Label name
                      extra:
                        color: hex code
                summary: Single Tree With Children
                description: 'This request body is JSON. For this JSON, it is the
                  list. <br/>Each list contains many dictionary of data. <br/>Each
                  dictionary of data means the one root tree.  Each root tree must
                  contain data. <br/>When the root tree has the children node, pass
                  children in the dictionary. <br/>data is the dictionary; each dictionary
                  of data must contain two parameters, name(string) and extra(dictionary).
                  <br/>children mean the children of the data, which is the list.
                  One children can contain many dictionary of data. '
              MultipleTreeWithChildren:
                value:
                - data:
                    name: Label name
                    extra:
                      color: hex code
                  children:
                  - data:
                      name: Label name
                      extra:
                        color: hex code
                - data:
                    name: Label name1
                    extra:
                      color: hex code
                summary: Multiple Tree With Children
                description: 'This request body is JSON. For this JSON, it is the
                  list. <br/>Each list contains many dictionary of data. <br/>Each
                  dictionary of data means the one root tree.  Each root tree must
                  contain data. <br/>When the root tree has the children node, pass
                  children in the dictionary. <br/>data is the dictionary; each dictionary
                  of data must contain two parameters, name(string) and extra(dictionary).
                  <br/>children mean the children of the data, which is the list.
                  One children can contain many dictionary of data. '
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          description: No response body
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              examples:
                NotFound:
                  value:
                    detail: Not found.
                    status: 404
                  summary: Not Found
                  description: 404 Not Found
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData.:
                  value:
                    detail: |-
                      Got KeyError when attempting to get a value for field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.
                      Original exception text was: 'workspace'.
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data.
                  description: Serializer format is not same as the RDB data.
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided.:
                  value:
                    detail: Authentication credentials were not provided.
                    code: not_authenticated
                  summary: Authentication credentials were not provided.
                  description: Authentication credentials were not provided.
                GivenTokenNotValidForAnyTokenType:
                  value:
                    detail: Given token not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token not valid for any token type
                  description: Given token is not valid for any token type.
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction.:
                  value:
                    detail: You do not have permission to perform this action.
                    code: permission_denied
                  summary: You do not have permission to perform this action.
                  description: You do not have permission to perform this action.
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                BadRequest:
                  value:
                    error:
                      code: bad_request
                      messages: duplicates children name in parent node
                  summary: Bad Request
                  description: Bad Request
          description: ''
    put:
      operationId: label_v3_labels_update
      description: Move source node to target node.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this label.
        required: true
      tags:
      - label
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelIDMoveRequest'
            examples:
              MoveNodeToTargetNode:
                value:
                  target: node_id
                summary: Move node to target node
                description: 'Move node to target node, target node id: 0 is meaning
                  root, other is default node id'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelIDMove'
              examples:
                ReturnTheLabelTreeByTheLabelId:
                  value:
                    data:
                    - data:
                        name: Label name
                        extra:
                          color: hex code
                      id: node id
                      children:
                      - data:
                          name: Label name
                          extra:
                            color: hex code
                        id: node id
                    count: 2
                  summary: Return the Label tree by the label id
                  description: Return the Label tree by the label id, the return list
                    will under the data.
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              examples:
                NotFound:
                  value:
                    detail: Not found.
                    status: 404
                  summary: Not Found
                  description: 404 Not Found
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData.:
                  value:
                    detail: |-
                      Got KeyError when attempting to get a value for field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.
                      Original exception text was: 'workspace'.
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data.
                  description: Serializer format is not same as the RDB data.
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided.:
                  value:
                    detail: Authentication credentials were not provided.
                    code: not_authenticated
                  summary: Authentication credentials were not provided.
                  description: Authentication credentials were not provided.
                GivenTokenNotValidForAnyTokenType:
                  value:
                    detail: Given token not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token not valid for any token type
                  description: Given token is not valid for any token type.
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction.:
                  value:
                    detail: You do not have permission to perform this action.
                    code: permission_denied
                  summary: You do not have permission to perform this action.
                  description: You do not have permission to perform this action.
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
          description: ''
    patch:
      operationId: label_v3_labels_partial_update
      description: Update the Label for the pk include the updating name, extra.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this label.
        required: true
      tags:
      - label
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedLabelIDRequest'
            examples:
              UpdateTheValueForTheNode:
                value:
                  name: Label name
                  extra:
                    color: hex code
                summary: Update the value for the node
                description: Update the value for the node, the return list will under
                  the data.
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelID'
              examples:
                ReturnTheLabelTreeByTheLabelId:
                  value:
                    data:
                    - data:
                        name: Label name
                        extra:
                          color: hex code
                      id: node id
                      children:
                      - data:
                          name: Label name
                          extra:
                            color: hex code
                        id: node id
                    count: 2
                  summary: Return the Label tree by the label id
                  description: Return the Label tree by the label id, the return list
                    will under the data.
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              examples:
                NotFound:
                  value:
                    detail: Not found.
                    status: 404
                  summary: Not Found
                  description: 404 Not Found
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData.:
                  value:
                    detail: |-
                      Got KeyError when attempting to get a value for field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.
                      Original exception text was: 'workspace'.
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data.
                  description: Serializer format is not same as the RDB data.
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided.:
                  value:
                    detail: Authentication credentials were not provided.
                    code: not_authenticated
                  summary: Authentication credentials were not provided.
                  description: Authentication credentials were not provided.
                GivenTokenNotValidForAnyTokenType:
                  value:
                    detail: Given token not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token not valid for any token type
                  description: Given token is not valid for any token type.
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction.:
                  value:
                    detail: You do not have permission to perform this action.
                    code: permission_denied
                  summary: You do not have permission to perform this action.
                  description: You do not have permission to perform this action.
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                BadRequest:
                  value:
                    error:
                      code: bad_request
                      messages: The target node is source node descendant
                  summary: Bad Request
                  description: Bad Request
          description: ''
    delete:
      operationId: label_v3_labels_destroy
      description: Delete the Label by the label id
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this label.
        required: true
      tags:
      - label
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              examples:
                NotFound:
                  value:
                    detail: Not found.
                    status: 404
                  summary: Not Found
                  description: 404 Not Found
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData.:
                  value:
                    detail: |-
                      Got KeyError when attempting to get a value for field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.
                      Original exception text was: 'workspace'.
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data.
                  description: Serializer format is not same as the RDB data.
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided.:
                  value:
                    detail: Authentication credentials were not provided.
                    code: not_authenticated
                  summary: Authentication credentials were not provided.
                  description: Authentication credentials were not provided.
                GivenTokenNotValidForAnyTokenType:
                  value:
                    detail: Given token not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token not valid for any token type
                  description: Given token is not valid for any token type.
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction.:
                  value:
                    detail: You do not have permission to perform this action.
                    code: permission_denied
                  summary: You do not have permission to perform this action.
                  description: You do not have permission to perform this action.
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
          description: ''
  /label/v3/schema/:
    get:
      operationId: root_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      security:
      - jwtAuth: []
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                SerializerFormatIsNotSameAsTheRDBData.:
                  value:
                    detail: |-
                      Got KeyError when attempting to get a value for field `workspace` on serializer `WorkflowBackendParamsSerializer`.
                      The serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.
                      Original exception text was: 'workspace'.
                    code: internal_server_error
                  summary: Serializer format is not same as the RDB data.
                  description: Serializer format is not same as the RDB data.
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided.:
                  value:
                    detail: Authentication credentials were not provided.
                    code: not_authenticated
                  summary: Authentication credentials were not provided.
                  description: Authentication credentials were not provided.
                GivenTokenNotValidForAnyTokenType:
                  value:
                    detail: Given token not valid for any token type
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    code: token_not_valid
                  summary: Given token not valid for any token type
                  description: Given token is not valid for any token type.
                GivenTokenNotValidForAPI:
                  value:
                    detail: User not found
                    code: user_not_found
                  summary: Given token not valid for API
                  description: Given token not valid for API
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction.:
                  value:
                    detail: You do not have permission to perform this action.
                    code: permission_denied
                  summary: You do not have permission to perform this action.
                  description: You do not have permission to perform this action.
          description: ''
components:
  schemas:
    Label:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          description: 'Label name: any string e.g., TUMOR.'
          maxLength: 255
        extra:
          type: object
          additionalProperties: {}
          description: 'optional, dictionary include color key, color use hex code
            to represent <br/>e.g. {"color": "#000000"}'
      required:
      - id
      - name
    LabelID:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          description: 'Label name: any string e.g., TUMOR.'
          maxLength: 255
        extra:
          type: object
          additionalProperties: {}
          description: 'optional, dictionary include color key, color use hex code
            to represent <br/>e.g. {"color": "#000000"}'
      required:
      - id
      - name
    LabelIDMove:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          readOnly: true
          description: 'Label name: any string e.g., TUMOR.'
        extra:
          type: object
          additionalProperties: {}
          readOnly: true
          description: 'optional, dictionary include color key, color use hex code
            to represent <br/>e.g. {"color": "#000000"}'
      required:
      - extra
      - id
      - name
    LabelIDMoveRequest:
      type: object
      properties:
        target:
          type: integer
          writeOnly: true
          description: Target node ID. <br/>Using 0 moves the node to root. Otherwise,
            it is moved to another node based on the node ID.
      required:
      - target
    LabelIDPostRequest:
      type: object
      properties:
        name:
          type: string
          description: 'Label name: any string e.g., TUMOR.'
          maxLength: 255
        extra:
          type: object
          additionalProperties: {}
          description: 'optional, dictionary include color key, color use hex code
            to represent <br/>e.g. {"color": "#000000"}'
        data:
          type: object
          additionalProperties: {}
          writeOnly: true
          description: 'The data uses the dictionary format. <br/>Each data must contain
            two parameters: name (string) and extra (dictionary). '
        children:
          type: object
          additionalProperties: {}
          writeOnly: true
          description: 'Children refers to child data objects. <br/>Each child may
            either contain a single data or a list of dictionaries. '
      required:
      - name
    LabelRequest:
      type: object
      properties:
        name:
          type: string
          description: 'Label name: any string e.g., TUMOR.'
          maxLength: 255
        extra:
          type: object
          additionalProperties: {}
          description: 'optional, dictionary include color key, color use hex code
            to represent <br/>e.g. {"color": "#000000"}'
        data:
          type: object
          additionalProperties: {}
          writeOnly: true
          description: 'The data uses the dictionary format. <br/>Each data must contain
            two parameters: name (string) and extra (dictionary). '
        children:
          type: object
          additionalProperties: {}
          writeOnly: true
          description: 'Children refers to child data objects.<br/> Each child may
            either contain a single data or a list of dictionaries. '
      required:
      - name
    NotFound:
      type: object
      properties:
        detail:
          type: string
          description: Detail of the error
      required:
      - detail
    PatchedLabelIDRequest:
      type: object
      properties:
        name:
          type: string
          description: 'Label name: any string e.g., TUMOR.'
          maxLength: 255
        extra:
          type: object
          additionalProperties: {}
          description: 'optional, dictionary include color key, color use hex code
            to represent <br/>e.g. {"color": "#000000"}'
    StandardSerializers:
      type: object
      properties:
        detail:
          type: string
          description: The detailed error message.
        msg:
          type: string
          default: Authentication credentials were not provided.
          description: A detailed error message.
        code:
          type: string
          description: The error code.
      required:
      - code
      - detail
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: Bearer
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
