openapi: 3.0.3
info:
  title: Atgenomix SeqsLab V3 platform API
  version: 3.0.0
  description: GA4GH-compliant RESTful API apps in Atgenomix SeqsLab platform, the
    cloud-native enterprise biomedical informatics platform.
paths:
  /htsget/v1/reads/{drs_id}/:
    get:
      operationId: htsget_v1_reads_retrieve
      description: retrieve htsget reads ticket and service-info
      parameters:
      - in: path
        name: drs_id
        schema:
          type: string
        required: true
      tags:
      - htsget
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HtsgetRequest'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided.:
                  value:
                    detail: Authentication credentials were not provided.
                    status: 401
                  summary: Authentication credentials were not provided.
                  description: Authentication credentials were not provided.
                GivenTokenNotValidForAnyTokenType:
                  value:
                    detail: Given token not valid for any token type
                    code: token_not_valid
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    status: 401
                  summary: Given token not valid for any token type
                  description: Given token is not valid for any token type.
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction.:
                  value:
                    detail: You do not have permission to perform this action.
                    status: 403
                  summary: You do not have permission to perform this action.
                  description: You do not have permission to perform this action.
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSerializers'
              examples:
                NotFound.:
                  value:
                    detail: Not found.
                    status: 404
                  summary: Not found.
                  description: Not found.
          description: ''
    post:
      operationId: htsget_v1_reads_create
      description: retrieve htsget reads ticket and service-info
      parameters:
      - in: path
        name: drs_id
        schema:
          type: string
        required: true
      tags:
      - htsget
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HtsgetRequestRequest'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HtsgetRequest'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided.:
                  value:
                    detail: Authentication credentials were not provided.
                    status: 401
                  summary: Authentication credentials were not provided.
                  description: Authentication credentials were not provided.
                GivenTokenNotValidForAnyTokenType:
                  value:
                    detail: Given token not valid for any token type
                    code: token_not_valid
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    status: 401
                  summary: Given token not valid for any token type
                  description: Given token is not valid for any token type.
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction.:
                  value:
                    detail: You do not have permission to perform this action.
                    status: 403
                  summary: You do not have permission to perform this action.
                  description: You do not have permission to perform this action.
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSerializers'
          description: ''
  /htsget/v1/reads/service-info/:
    get:
      operationId: htsget_v1_reads_service_info_retrieve
      description: retrieve htsget reads ticket and service-info
      tags:
      - htsget
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInfo'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided.:
                  value:
                    detail: Authentication credentials were not provided.
                    status: 401
                  summary: Authentication credentials were not provided.
                  description: Authentication credentials were not provided.
                GivenTokenNotValidForAnyTokenType:
                  value:
                    detail: Given token not valid for any token type
                    code: token_not_valid
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    status: 401
                  summary: Given token not valid for any token type
                  description: Given token is not valid for any token type.
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction.:
                  value:
                    detail: You do not have permission to perform this action.
                    status: 403
                  summary: You do not have permission to perform this action.
                  description: You do not have permission to perform this action.
          description: ''
  /htsget/v1/schema/:
    get:
      operationId: root_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      security:
      - jwtAuth: []
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided.:
                  value:
                    detail: Authentication credentials were not provided.
                    status: 401
                  summary: Authentication credentials were not provided.
                  description: Authentication credentials were not provided.
                GivenTokenNotValidForAnyTokenType:
                  value:
                    detail: Given token not valid for any token type
                    code: token_not_valid
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    status: 401
                  summary: Given token not valid for any token type
                  description: Given token is not valid for any token type.
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction.:
                  value:
                    detail: You do not have permission to perform this action.
                    status: 403
                  summary: You do not have permission to perform this action.
                  description: You do not have permission to perform this action.
          description: ''
  /htsget/v1/variants/{drs_id}/:
    get:
      operationId: htsget_v1_variants_retrieve
      description: retrieve htsget variants ticket and service-info
      parameters:
      - in: path
        name: drs_id
        schema:
          type: string
        required: true
      tags:
      - htsget
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HtsgetRequest'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided.:
                  value:
                    detail: Authentication credentials were not provided.
                    status: 401
                  summary: Authentication credentials were not provided.
                  description: Authentication credentials were not provided.
                GivenTokenNotValidForAnyTokenType:
                  value:
                    detail: Given token not valid for any token type
                    code: token_not_valid
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    status: 401
                  summary: Given token not valid for any token type
                  description: Given token is not valid for any token type.
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction.:
                  value:
                    detail: You do not have permission to perform this action.
                    status: 403
                  summary: You do not have permission to perform this action.
                  description: You do not have permission to perform this action.
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSerializers'
              examples:
                NotFound.:
                  value:
                    detail: Not found.
                    status: 404
                  summary: Not found.
                  description: Not found.
          description: ''
    post:
      operationId: htsget_v1_variants_create
      description: retrieve htsget variants ticket and service-info
      parameters:
      - in: path
        name: drs_id
        schema:
          type: string
        required: true
      tags:
      - htsget
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HtsgetRequestRequest'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HtsgetRequest'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided.:
                  value:
                    detail: Authentication credentials were not provided.
                    status: 401
                  summary: Authentication credentials were not provided.
                  description: Authentication credentials were not provided.
                GivenTokenNotValidForAnyTokenType:
                  value:
                    detail: Given token not valid for any token type
                    code: token_not_valid
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    status: 401
                  summary: Given token not valid for any token type
                  description: Given token is not valid for any token type.
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction.:
                  value:
                    detail: You do not have permission to perform this action.
                    status: 403
                  summary: You do not have permission to perform this action.
                  description: You do not have permission to perform this action.
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSerializers'
          description: ''
  /htsget/v1/variants/service-info/:
    get:
      operationId: htsget_v1_variants_service_info_retrieve
      description: retrieve htsget variants ticket and service-info
      tags:
      - htsget
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInfo'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorSerializers'
              examples:
                AuthenticationCredentialsWereNotProvided.:
                  value:
                    detail: Authentication credentials were not provided.
                    status: 401
                  summary: Authentication credentials were not provided.
                  description: Authentication credentials were not provided.
                GivenTokenNotValidForAnyTokenType:
                  value:
                    detail: Given token not valid for any token type
                    code: token_not_valid
                    messages:
                    - token_class: AccessToken
                      token_type: access
                      message: Token is invalid or expired
                    status: 401
                  summary: Given token not valid for any token type
                  description: Given token is not valid for any token type.
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSerializers'
              examples:
                YouDoNotHavePermissionToPerformThisAction.:
                  value:
                    detail: You do not have permission to perform this action.
                    status: 403
                  summary: You do not have permission to perform this action.
                  description: You do not have permission to perform this action.
          description: ''
components:
  schemas:
    ClassEnum:
      enum:
      - header
      type: string
    ErrorSerializers:
      type: object
      properties:
        status_code:
          type: integer
          description: The integer representing the HTTP status code.
        detail:
          type: string
          description: A detailed error message.
      required:
      - detail
      - status_code
    FormatEnum:
      enum:
      - BAM
      - CRAM
      - VCF
      - BCF
      type: string
    HtsgetRequest:
      type: object
      description: serialize htsget request.
      properties:
        format:
          $ref: '#/components/schemas/FormatEnum'
        fields:
          type: array
          items:
            type: string
        tags:
          type: array
          items:
            type: string
        notags:
          type: array
          items:
            type: string
        regions:
          type: array
          items:
            $ref: '#/components/schemas/Region'
        class:
          $ref: '#/components/schemas/ClassEnum'
    HtsgetRequestRequest:
      type: object
      description: serialize htsget request.
      properties:
        format:
          $ref: '#/components/schemas/FormatEnum'
        fields:
          type: array
          items:
            type: string
        tags:
          type: array
          items:
            type: string
        notags:
          type: array
          items:
            type: string
        regions:
          type: array
          items:
            $ref: '#/components/schemas/RegionRequest'
        class:
          $ref: '#/components/schemas/ClassEnum'
    Region:
      type: object
      description: |-
        Regions to return.
        If not present, the entire file will be returned.
        When present, the array must contain at least one region specification.
        Note that regions will be returned in the order that they appear in the file,
        which may not match the order in the list. Any overlapping regions will be merged.
      properties:
        referenceName:
          type: string
        start:
          type: integer
          minimum: 0
        end:
          type: integer
          minimum: 1
      required:
      - referenceName
    RegionRequest:
      type: object
      description: |-
        Regions to return.
        If not present, the entire file will be returned.
        When present, the array must contain at least one region specification.
        Note that regions will be returned in the order that they appear in the file,
        which may not match the order in the list. Any overlapping regions will be merged.
      properties:
        referenceName:
          type: string
        start:
          type: integer
          minimum: 0
        end:
          type: integer
          minimum: 1
      required:
      - referenceName
    ServiceInfo:
      type: object
      description: serialize htsget service info.
      properties:
        id:
          type: string
          maxLength: 255
        name:
          type: string
          maxLength: 255
        description:
          type: string
          maxLength: 1023
        type:
          type: object
          additionalProperties: {}
        organization:
          type: object
          additionalProperties: {}
        url:
          type: string
          format: uri
          maxLength: 200
        version:
          type: string
          maxLength: 16
        htsget:
          type: object
          additionalProperties: {}
      required:
      - description
      - id
      - name
      - url
    UnauthorizedErrorSerializers:
      type: object
      properties:
        status_code:
          type: integer
          default: 401
          description: The integer representing the HTTP status code.
        msg:
          type: string
          default: Authentication credentials were not provided.
          description: A detailed error message.
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: Bearer
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
